### ISSUE TITLE
Match algo issues

### ISSUE THREAD

**Issue by zubuzon** [isiahmeadows/thallium#12]
@isiahmeadows Your match algo. I went throught it now line-by-line

- Transitive equivalence for circular references of arrays doesn't work at all.
- arrays with identical values but different non-index properties are not seen as equal
- array buffer comparison fails. In the example below it should have returned false. Returns true!

```js
        var buffer1 = new ArrayBuffer(4);
        var buffer2 = new ArrayBuffer(8);
```
- no dataView and arrayBuffer support

**Error comparison fails:**

```js
// Different instances, so should have been false
strict(new Error('foo'), new Error('foo')))
```
**Map() and Set() have issues as well.**

Map iterators are missing, and this code (*same code breaks for Set()*):

```js
     let mapA = new Map();
     let mapB = new Map();
     mapA.set('a', 1);
     mapA.set('b', 2);
     mapA.set('c', 3);

     mapB.set('a', 1);
     mapB.set('b', 2);
     mapB.set('c', 3);
strict(mapA, mapB)  // returns true, should have returned false
    });
```

### Other things to mention

**only take 3 arguments, but used 4 here**

`result = matchSet(a, b, strict, count)`

**not allowed to overwrite defaults**

`var Uint8Array = global.Uint8Array;`

In nodeJS  Uint8Array exist already as a variable, you are overwriting it. You can check this if you remove you own variabels. Still the code will not fail.

**Comment by zubuzon** [comment]
@isiahmeadows Here are few more things. When I look into this I compare with ECMA specs

- arguments doesn't returns false given an object - `strict({}, arguments)`. Returns true

- arrow functions fails

- function comparison fails. Look at this. There is an difference here  because the first one is bound to the context / environment. The second isn't

```js
// should return false
strict(() => {}, function() {}); // true 
```
- Set() have issues with different entries

```js
 let setA = new Set();
     let setB = new Set();
     setA.add('a');
     setA.add('b');
     setA.add('c');
     setB.add('d');
     setB.add('e');
     setB.add('f');
   strict(setA.entries(), setB.entries()) // expected to be false, returns true
```

**Comment by zubuzon** [comment]
@isiahmeadows Here is a few more things to look into:

```js
// different instance. Should return false, but returns true
strict({x: new Date('1972-08-01')}, {x: new Date('1972-08-01')})

// should return false for arrays with different values, but returns true
strict(new Int8Array(1, 2, 3, 4), new Int8Array(4, 2, 3, 4))

// this fails for typed arrays

[
            [new Uint8Array(1e5), new Uint8Array(1e5)],
            [new Uint16Array(1e5), new Uint16Array(1e5)],
            [new Uint32Array(1e5), new Uint32Array(1e5)],
            [new Uint8ClampedArray(1e5), new Uint8ClampedArray(1e5)],
            [new Int8Array(1e5), new Int8Array(1e5)],
            [new Int16Array(1e5), new Int16Array(1e5)],
            [new Int32Array(1e5), new Int32Array(1e5)],
            [new Float32Array(1e5), new Float32Array(1e5)],
            [new Float64Array(1e5), new Float64Array(1e5)],
            [new Int16Array(256), new Uint16Array(256)],
            [new Int16Array([256]), new Uint16Array([256])],
            [new Float32Array([+0.0]), new Float32Array([-0.0])],
            [new Float64Array([+0.0]), new Float32Array([-0.0])],
            [new Float64Array([+0.0]), new Float64Array([-0.0])],
            [new Uint8Array([1, 2, 3, 4]).subarray(1), new Uint8Array([2, 3, 4])],
            [new Uint16Array([1, 2, 3, 4]).subarray(1), new Uint16Array([2, 3, 4])],
            [new Uint32Array([1, 2, 3, 4]).subarray(1, 3), new Uint32Array([2, 3])]
        ].forEach((arrayPair: any, idx: any) => {
            it('equalArrayPairs - ' + idx, () => {
                expect(strict(arrayPair[0], arrayPair[1])).to.be.true; // return false for 3 of the values
            });
        });
```

**Comment by zubuzon** [comment]
@isiahmeadows I was trying to figure out how you could add support for iterators, but you are blocking yourself 3 different places in the source, so without a rewrite it will be hard. Easiest to check for this is together with Object keys, but you never reach so far down in your code because of a few road blockers, and you are checking for objectProto. So you will not even reach down to `innerMatch`

Generators seems to be hard too, if you study what I wrote above.

Any ideas?

**Comment by isiahmeadows** [comment]
Welp...a few more runtime checks. But I'd like to comment on each thing you mentioned (I'd prefer if you filed these separately BTW):

1. I ripped out special handling of `arguments` values, mainly because there was little to be gained. It stems from the fact that in strict mode, they are actually themselves just plain objects with an `undefined` internal slot.
2. ArrayBuffers can easily be compared by wrapping them in a Uint8Array, but I agree it probably should be comparable.
3. I may have fixed the function issue in my next-to-latest patch, but I'm not sure I could've repro'd it anyways.
4. I match dates by the time they represent. `match(new Date("1980-10-13"), new Date("1980-10-13")) === true` is intentional, and won't change.
5. I fixed the typed array issue in my next-to-latest patch, but my latest patch includes DataViews and is much more generic. To be fair, `node-deep-equal` and even Chai's `deep-eql` don't check typed arrays correctly, just buffers. It seems Node's `assert` is the exception, not the rule here.
6. I decided to rip out all the extra props checking. Expando properties on arrays/etc. are a bad idea, anyways, and Array subclasses are also rare. That was the main slowdown, to be honest, and it's incredibly rare to even have those. If those really need checked, there's other ways to check it (e.g. `t.hasKeys`), and subclassing is itself fragile, anyways - see the Java community's big shift from inheritance to composition.
7. `Symbol.iterator` support has just now landed. That will fix generator instances, `Set.prototype.entries`, `Map.prototype.{keys,values}`, `Array.prototype.entries`, etc. If it's an iterable, it can be iterated.
  - Furthermore, this also works for functions that implement the iterator protocol (which otherwise are checked for identity only), but not for strings.
  - This wound up adding another item on my "do at some point" list - rewrite this completely to be based on the iterator protocol (and gracefully degrade as necessary).

-----

I will note that every feature has a cost. And since this algorithm is naturally very generic and polymorphic, it can slow down easily.

Also, the tests for the matching [have always sucked and cover virtually nothing](https://github.com/isiahmeadows/thallium/blob/master/test/assertions/match.js), but I seriously should quit procrastinating and fix that.

**Comment by zubuzon** [comment]
A drug addict broke into my house so i will respond to this email soon as i
have sorted things out

**Comment by zubuzon** [comment]
@isiahmeadows I got things under control now. I have my own tests I ran to check your algorithm, therefor I found the isues I mentioned. However I ran a quick benchmark, and your object iteration performance dropped with around 64%.

```js

// today
object literal              x 739,302 ops/sec ±0.58% (89 runs sampled)

// before
object literal              x 3,096,062 ops/sec ±1.25% (85 runs sampled)
```
As allways! Great work  👍

**Comment by isiahmeadows** [comment]
Check the latest push. That does verify lengths and other things. (The object literal drop was because of the `Symbol.iterator` checks, but I removed those - you can always compare with `Array.from`, and conveniently also get a more useful output.)

**Comment by isiahmeadows** [comment]
To recap everything here:

> - Transitive equivalence for circular references of arrays doesn't work at all.
> - arrays with identical values but different non-index properties are not seen as equal
> - array buffer comparison fails. In the example below it should have returned false. Returns true!
> - no dataView and arrayBuffer support

All fixed

> - Error comparison fails:
>
>   ```js
>   // Different instances, so should have been false
>   strict(new Error('foo'), new Error('foo')))
>   ```

The message is the same, and is also, in fact, an own, enumerable property. I personally use that ability to compare errors structurally extensively within this project ([this is but one of the many cases](https://github.com/isiahmeadows/thallium/blob/d32ef1dc093eaee43f37448ce1e08c805e36dd87/test/core/reporters.js#L495-L513)).

I just pushed a fix for `match(new Error("foo"), {message: "foo"})` and `match(new Error("foo"), new TypeError("foo"))`, both of which should have failed, but neither did.

> - only take 3 arguments, but used 4 here

That was an accident I caught on my own.

> not allowed to overwrite defaults

See [this comment](https://github.com/isiahmeadows/thallium/issues/13#issuecomment-249396772). I'm not overwriting anything.

> - arguments doesn't returns false given an object
> - arrow functions fails
> - function comparison fails.

All fixed. The latter two were because of awkward logic regarding functions, which no longer exists now.

> - Set() have issues with different entries

`Symbol.iterator` is not supported, so this isn't a bug. Use `match(set1, set2)` or `match([...set1.entries], [...set2.entries()])`.

> - `strict({x: new Date('1972-08-01')}, {x: new Date('1972-08-01')})`

I'm comparing the date's values, not their wrapper objects. Primitives (except for Symbols in non-strict matching) are always compared by strict equality except for `NaN`s being considered equivalent.

> - `strict(new Int8Array(1, 2, 3, 4), new Int8Array(4, 2, 3, 4))`

The arrays are constructed incorrectly. In the case of `strict(new Int8Array([1, 2, 3, 4]), new Int8Array([4, 2, 3, 4]))`, that fails as expected because the values are different. Typed arrays are checked just like normal arrays; I can just specialize how I check them.

> - `[new Uint8Array([1, 2, 3, 4]).subarray(1), new Uint8Array([2, 3, 4])],`
> - etc.

Should be fixed, since I just access them by index now.

--------

At this point, since everything here has been addressed and resolved, I'm closing.
