### ISSUE TITLE
feature detection performance

### ISSUE THREAD

**Issue by zubuzon** [isiahmeadows/thallium#14]
I think maybe you get a better performance if you check things this way:

```js

// PrototypeOf
var supportPrototypeOf = typeof Object.getPrototypeOf === 'function';

// Symbol
var supportSymbol = typeof Symbol !== undefined;

// Symbol iterator
var supportSymbolIterator = supportSymbol && typeof Symbol.iterator !== undefined;

// Symbol toStringTag 
var supportSymbolToStringTag = supportSymbol && typeof Symbol.toStringTag !== undefined;

// Set
var supportSet = typeof Set !== undefined;

// Set entries
var supportSetEntries = supportSet && typeof Set.prototype.entries === 'function';
// Map
var supportMap = typeof Map !== undefined;

// Map entries
var supportMapEntries = supportMap && typeof Map.prototype.entries === 'function';

// Set entries prototype
var setIteratorPrototype = supportPrototypeOf && supportSetEntries && Object.getPrototypeOf(new Set().entries());

// Map entries prototype
var mapIteratorPrototype = supportPrototypeOf && supportMapEntries && Object.getPrototypeOf(new Map().entries());

// Array iterator
var supportArrayIterator = supportSymbolIterator && typeof Array.prototype[Symbol.iterator] === 'function';

// Array iterator prototype
var supportArrayIteratorPrototype = supportArrayIterator && Object.getPrototypeOf([][Symbol.iterator]());

// String iterator
var supportStringIterator = supportSymbolIterator && typeof Array.prototype[Symbol.iterator] === 'function';

// String iterator prototype
var supportStringIteratorPrototype = supportStringIterator && Object.getPrototypeOf(''[Symbol.iterator]());
```

**Comment by zubuzon** [comment]
@isiahmeadows Are you supporting everything listed above?

**Comment by isiahmeadows** [comment]
Let me go down the list:

1. `Object.getPrototypeOf` - My baseline is ES5 (so really old Safaris and IEs aren't supported normally). If you don't have this, it's likely easy to polyfill.
2. `Symbol` - Already detected, but I only need to detect it for `core-js`'s almost-polyfill, so those are checked correctly.
3. `Symbol.iterator` - I chose to intentionally not support it because it slows everything down.
4. `Symbol.toStringTag` - I literally don't have any need for it, since I only care about the internal [[Class]] of `arguments`. Any other use is pointless because if you need that kind of matching, you'd probably already prefer the strict matching.
5. `Map` and `Set` - Already detected, because not all Node versions supported have that.
6. `Map.prototype.entries`, `Set.prototype.entries` - See my remarks on `Symbol.iterator`.
7. `Array.prototype[Symbol.iterator]`, `String.prototype[Symbol.iterator]`, etc. - See my remarks on `Symbol.iterator`.
8. `Object.getPrototypeOf(array[Symbol.iterator]())` - See my remarks on `Symbol.iterator`.

So yes, everything above has already been covered.
