### ISSUE TITLE
doesn't treat objects created by `Object.create(null)` like a plain object

### ISSUE THREAD

**Issue by zubuzon** [isiahmeadows/thallium#25]
Try this

```js
  function Foo() {
        this.a = 1;
      }
      Foo.prototype.constructor = null;

      var object1 = create(null);
      object1.a = 1;

      var object2 = { 'a': 1 };

     strictl(object1, object2) // should return true
    strict(new Foo, object2) // should return false
```

**Comment by isiahmeadows** [comment]
It's not documented yet, but the key difference to why this doesn't work is because they have different prototypes. `t.match` will work, though, and `t.deepEqual(Object.create(null), {})` throwing is expected behavior (it's equivalent to `t.deepEqual(Object.create(null), Object.create(Object.prototype))`.
