### ISSUE TITLE
match issues again

### ISSUE THREAD

**Issue by zubuzon** [isiahmeadows/thallium#41]
Hi. I'm still recovering, but was looking into Thallium code again. And when I was checking the match algo, I found minor issues
E.g.  Nested entries isn't suppoted. 

```js
  var setA = new Set();
      var setB = new Set();
      setA.add([ [], [], [] ]);
      setB.add([ [], [], [] ]);
```

This one should have returned true, but returns false.

And this one:

```js
// circular Sets
  var setA = new Set();
      var setB = new Set();
      setA.add(setB);
      setB.add(setA);
```
SetA and SetB should have been equal, but are seen as falsy.

Same issues found for Map().

```js
// should be seen as equal, but they are not
 new Map([[{foo: 'bar'}, 'bar']]),
new Map([[{foo: 'bar'}, 'bar']]),
```
Any plans to add back iterator support?

**Comment by isiahmeadows** [comment]
In the first case (array matching), check if the contents themselves match:

```js
var a = [[], [], []]
var b = [[], [], []]

match.match(a, b) // should be true
```

In the second case, that's by design. The circular references to each other
are not of the same depth. Here's how they reference each other in the eyes
of the matching algorithm:

```
setA -> setB -> setA -> setB -> ...
setB -> setA -> setB -> setA -> ...
```

As for iterators, I have no plans on adding back support for them.

**Comment by isiahmeadows** [comment]
BTW, the first case doesn't repro locally, and the second case [mirrors an exact test case](https://github.com/isiahmeadows/thallium/blob/master/test/assert/match.js#L458-L461) that is currently passing.
